server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  client:
    register-With-Eureka: false
    fetch-Registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  application:
    name: eurka-server
#  freemarker:
#    template-loader-path: classpath:/templates/
#    prefer-file-system-access : false

