eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8080
spring:
  application:
    name: service-zuul
  redis:
    host: 118.89.64.195
    port: 6379
    password:
    pool:
      maxIdle: 300
      maxActive: 600
      maxWait: 1000
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
zuul:
  routes:
    api-a:
      path: /**
      serviceId: service-usermodel
      sensitiveHeaders: "*"
#    api-b:
#      path: /api-b/**
#      serviceId: service-feign




