server:
  port: 8762
spring:
  datasource:
    url: jdbc:mysql://118.89.64.195:3306/Businiess
    username: root
    password: wang1818
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service-UserModel
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

redis:
  host: 118.89.64.195
  #访问端口
  port: 6379
  #注意，如果没有password，此处不设置值，但这一项要保留
  password:
  #最大空闲数，数据库连接的最大空闲时间。超过空闲时间，数据库连接将被标记为不可用，然后被释放。设为0表示无限制。
  maxIdle:  300
  #连接池的最大数据库连接数。设为0表示无限制
  maxActive: 600
  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
  maxWait: 1000

