server:
  port: 8762
spring:
  datasource:
    url: jdbc:mysql://118.89.64.195:3306/Businiess
    username: root
    password: wang1818
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service-UserModel
  redis:
    host: 118.89.64.195
    port: 6379
    password:
    pool:
      maxIdle: 300
      maxActive: 600
      maxWait: 1000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


