
server:
  port: 8760
spring:
  datasource:
    url: jdbc:mysql://118.89.64.195:3306/Businiess
    username: root
    password: wang1818
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: service-goodsmodel
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/